from typing import Protocol


class Visualizer(Protocol):
    def load_model(self, data: str): ...

    def add_segmentation(self, seg_path: str): ...

    def remove_segmentation(self): ...

    def call_render(self): ...

    def cleanup(self): ...

    def toggle_label_visibility(self, label_idx: int, visible: bool): ...
